### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by JYoon2K** [sooheang/kaps#5]
Dear all,

I have encountered the following problem. There seems to be an issue with *.o file format. You can see a discussion on the exactly same issue on the following webpage.

https://stackoverflow.com/questions/37189183/o-file-format-not-recognized-on-windows-7

The following is what happens if I try to install the packate. I would appreciate any advice. 

**> devtools::install_github("sooheang/kaps", force = T)**
Downloading GitHub repo sooheang/kaps@master
from URL https://api.github.com/repos/sooheang/kaps/zipball/master
Installing kaps
"C:/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/AAA/AppData/Local/Temp/RtmpGgL1dC/devtools3eb05c51377/sooheang-kaps-7ba94fa" --library="C:/Users/AAA/Documents/R/win-library/3.4"  \
  --install-tests 

* installing *source* package 'kaps' ...
** libs

*** arch - i386
**C:\Rtools\mingw_32\bin\nm.exe: combnC.o: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: combnPrimC.o: File format not recognized
C:\Rtools\mingw_32\bin\nm.exe: registerDynamicSymbols.o: File format not recognized**
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o kaps.dll tmp.def combnC.o combnPrimC.o registerDynamicSymbols.o -LC:/R/R-34~1.3/bin/i386 -lRlapack -LC:/R/R-34~1.3/bin/i386 -lRblas -lgfortran -lm -lquadmath -LC:/R/R-34~1.3/bin/i386 -lR
combnC.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'kaps'
* removing 'C:/Users/AAA/Documents/R/win-library/3.4/kaps'
In R CMD INSTALL
**Installation failed: Command failed (1)**
> 
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.3  R6_2.2.2        tools_3.4.3     withr_2.1.0     curl_3.0        memoise_1.1.0   git2r_0.19.0    digest_0.6.12  
[10] devtools_1.13.4

**Comment by sooheang** [comment]
Got it, thank you. 
We fixed it. Try 
``` r
 devtools::install_github("sooheang/kaps", ref = 'v1.1.4', force = TRUE) 
```

**Comment by JYoon2K** [comment]
Thanks a lot. Have a nice day.
