### ISSUE TITLE
Error: ‘surv_test’ is defunct.  Use ‘logrank_test’ instead.

### ISSUE THREAD

**Issue by prerna-khanna** [sooheang/kaps#8]
While using the default example, there is an error with:`f <- kaps(survival::Surv(time, status) ~ meta, data = toy, K = 3)`.
Here is the complete stack trace:

> 7: stop(errorCondition(msg, old = fname, new = new, package = package, 
>        class = "defunctError"))
> 6: .Defunct(msg = paste(sQuote("surv_test"), "is defunct.  Use", 
>        sQuote("logrank_test"), "instead."))
> 5: surv_test(formula = formula1, data = dat.perm, distribution = approximate(B = minors@N.perm))
> 4: FUN(X[[i]], ...)
> 3: lapply(X = X, FUN = FUN, ...)
> 2: sapply(fit, kaps.perm, permute = TRUE)
> 1: kaps(survival::Surv(time, status) ~ meta, data = toy, K = 3)

**Comment by sooheang** [comment]
Due to the CRAN policy, KAPS updated version cannot be updated on CRAN. Would you like to install the GitHub version as follows?

```
if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("sooheang/kaps")
```
